// Email service using Resend
// Stub: ready to activate when RESEND_API_KEY is set

interface EmailOptions {
  to: string | string[];
  subject: string;
  html: string;
  from?: string;
}

export async function sendEmail(options: EmailOptions): Promise<{ success: boolean; error?: string }> {
  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey || apiKey === "re_your_resend_api_key") {
    console.log("[Email Stub] Would send email:", {
      to: options.to,
      subject: options.subject,
    });
    return { success: true };
  }

  try {
    const { Resend } = await import("resend");
    const resend = new Resend(apiKey);

    const from = options.from ?? "DocDime <noreply@docdime.com>";
    const to = Array.isArray(options.to) ? options.to : [options.to];

    const result = await resend.emails.send({
      from,
      to,
      subject: options.subject,
      html: options.html,
    });

    if (result.error) {
      return { success: false, error: result.error.message };
    }

    return { success: true };
  } catch (error) {
    console.error("[Email] Send error:", error);
    return { success: false, error: "Failed to send email" };
  }
}

export function renderTemplate(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (match, key) => vars[key] ?? match);
}

export async function sendInvoiceEmail(params: {
  to: string;
  businessName: string;
  customerName: string;
  docNumber: string;
  amount: string;
  dueDate: string;
  pdfUrl?: string;
}) {
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: #2563eb; color: white; padding: 24px; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0; font-size: 24px;">Invoice ${params.docNumber}</h1>
        <p style="margin: 4px 0 0; opacity: 0.8;">from ${params.businessName}</p>
      </div>
      <div style="padding: 24px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
        <p>Dear ${params.customerName},</p>
        <p>Please find your invoice <strong>${params.docNumber}</strong> for <strong>${params.amount}</strong>.</p>
        <p><strong>Due Date:</strong> ${params.dueDate}</p>
        ${params.pdfUrl ? `<p><a href="${params.pdfUrl}" style="background: #2563eb; color: white; padding: 10px 20px; border-radius: 4px; text-decoration: none;">View Invoice PDF</a></p>` : ""}
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
        <p style="color: #6b7280; font-size: 12px;">Generated by DocDime</p>
      </div>
    </div>
  `;

  return sendEmail({
    to: params.to,
    subject: `Invoice ${params.docNumber} from ${params.businessName}`,
    html,
  });
}

export async function sendOverdueEmail(params: {
  to: string;
  businessName: string;
  customerName: string;
  docNumber: string;
  amount: string;
}) {
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: #dc2626; color: white; padding: 24px; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0; font-size: 24px;">Overdue Invoice ${params.docNumber}</h1>
      </div>
      <div style="padding: 24px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
        <p>Dear ${params.customerName},</p>
        <p>Invoice <strong>${params.docNumber}</strong> for <strong>${params.amount}</strong> is now <strong style="color: #dc2626;">overdue</strong>.</p>
        <p>Please make payment at your earliest convenience.</p>
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
        <p style="color: #6b7280; font-size: 12px;">Generated by DocDime</p>
      </div>
    </div>
  `;

  return sendEmail({
    to: params.to,
    subject: `Overdue Invoice ${params.docNumber} - Action Required`,
    html,
  });
}
